CREATE OR ALTER PROCEDURE [ETL].[USP_FILE_EXTRACT_STATS] 
	@EXTRACT_FILE_NAME VARCHAR(200), 
	@EXTRACT_FILE_PATH VARCHAR(200), 
	@CREATE_BID VARCHAR(200), 
	@PACKAGEAUDITID VARCHAR(200), 
	@FILE_TYPE_ID INT,
	@FILE_STATUS INT,
	@FILE_SOURCE_ID INT,
	@FILE_LOAD_ID INT OUTPUT
AS
/* ********************************************************************** 
Procedure Name: ETL.usp_INSERT_STAGE_FILE_STATS
Author:  EBaity & Bridgetree Analyst
Creation Date: 20180602
Desc: Loads records into STAGE.FILE_STATS
*************************************************************************
 

Change History
DATE		CHANGED BY		DESCRIPTION
	
*/
BEGIN
	--POPULATE FILE STATS TABLE
	INSERT INTO ASO_STG.AUDIT.FILE_LOAD_STATS
	(
		FILE_LOAD_DTM,
		FILE_TYPE_ID,
		FILE_SOURCE_ID,
		EXTRACT_FILE_NAME,
		EXTRACT_FILE_PATH,
		CREATE_BID,
		PACKAGEAUDITID,
		STATUS_ID
	)
	VALUES
	(
		GETDATE(),
		@FILE_TYPE_ID,
		@FILE_SOURCE_ID,
		@EXTRACT_FILE_NAME,
		@EXTRACT_FILE_PATH,
		@CREATE_BID,
		CAST(@PACKAGEAUDITID AS VARBINARY(MAX)),
		@FILE_STATUS
	)

	--RETURN SCOPE
	SELECT @FILE_LOAD_ID = SCOPE_IDENTITY();
END

